name = "thai-bingo-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [{ name = "BINGO_ROOM", class_name = "BingoRoom" }]

[[migrations]]
tag = "v1"
new_classes = ["BingoRoom"]
